<a href="https://colab.research.google.com/github/taharamay123/my-codes/blob/main/1_55_02_2_56_21.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np

In [9]:
x_1=([1,3,4],[5,6,7])
x_2=([4,5,6],[1,5,6],[5,3,9])
tf.linalg.matmul(
    x_1,
    x_2,
    transpose_a=False,
    transpose_b=False,
    adjoint_a=False,
    adjoint_b=False,
    a_is_sparse=False,
    b_is_sparse=False,
    output_type=None,
    name=None
)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 27,  32,  60],
       [ 61,  76, 129]], dtype=int32)>

In [5]:
print(tf.transpose(x_1))

tf.Tensor(
[[1 5]
 [3 6]
 [4 7]], shape=(3, 2), dtype=int32)


In [17]:
x1=tf.constant([[[1,2,0],
               [3,5,-1]],
               [[10,2,0],
              [1,0,2]],
              [[5,8,0],
              [2,7,0]],
             [[2,1,9],
            [4,-3,32]]])

x2=tf.constant([[[1,2,0],
                [3,5,-1],
                 [4,5,7]],
                [[10,2,0],
                [1,0,2],
                 [4,5,7]],
                [[5,8,0],
                [2,7,0],
                 [4,5,7]],
                [[2,1,9,],
              [4,-3,32],
                 [4,5,7]]])
tf.linalg.matmul(
    x1,
    x,
    transpose_a=False,
    transpose_b=False,
    adjoint_a=False,
    adjoint_b=False,
    a_is_sparse=False,
    b_is_sparse=False,
    output_type=None,
    name=None
)

<tf.Tensor: shape=(4, 2, 3), dtype=int32, numpy=
array([[[  7,  12,  -2],
        [ 14,  26, -12]],

       [[102,  20,   4],
        [ 18,  12,  14]],

       [[ 41,  96,   0],
        [ 24,  65,   0]],

       [[ 44,  44, 113],
        [124, 173, 164]]], dtype=int32)>

In [9]:
x1=tf.constant([[1,2,0],
               [3,5,-1],
               [10,2,0]],dtype=tf.float32)
x11=tf.linalg.inv(x1)
print(x11)

tf.Tensor(
[[-0.11111111  0.          0.11111111]
 [ 0.5555556  -0.         -0.05555556]
 [ 2.4444444  -1.          0.05555556]], shape=(3, 3), dtype=float32)


In [2]:

print(tf.linalg.svd(x1))

NameError: ignored