<a href="https://colab.research.google.com/github/taharamay123/my-codes/blob/main/1_7_1_55.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
tensor_indexed=tf.constant([2,3,4,5,6,7,8,9,10])
print(tensor_indexed)
print(tensor_indexed[0:5])
print(tensor_indexed[2:6])
print(tensor_indexed[1:8:3])

tf.Tensor([ 2  3  4  5  6  7  8  9 10], shape=(9,), dtype=int32)
tf.Tensor([2 3 4 5 6], shape=(5,), dtype=int32)
tf.Tensor([4 5 6 7], shape=(4,), dtype=int32)
tf.Tensor([3 6 9], shape=(3,), dtype=int32)


Multi dimensional arrays

In [3]:
tensor_two_d=tf.constant([[1,2,3],
                  [4,5,6],
                  [7,8,9],
                  [10,11,12]])
print(tensor_two_d[-1,0:3])

tf.Tensor([10 11 12], shape=(3,), dtype=int32)


In [4]:
tensor_three_d=tf.constant([
    [[1,2,3],
    [4,5,6],],
 [   [7,8,9],
    [10,11,12],
]
])
print(tensor_three_d[0,0:2,0:2])

tf.Tensor(
[[1 2]
 [4 5]], shape=(2, 2), dtype=int32)


In [5]:

x = tf.constant([-2.25, 3.25])

In [12]:
x_arg=([2,20,32,4])
print(tf.math.argmax(x_arg))

tf.Tensor(2, shape=(), dtype=int64)


In [13]:
print(tf.math.argmin(x_arg))

tf.Tensor(0, shape=(), dtype=int64)


In [22]:
tensor_two_d=tf.constant([[1,2,3],
                  [4,5,6],
                  [7,8,900],
                  [10,1,12]])
print(tf.math.argmin(tensor_two_d,axis=1))

tf.Tensor([0 0 0 1], shape=(4,), dtype=int64)


In [25]:
print(tf.pow(tensor_two_d,tensor_two_d))

tf.Tensor(
[[         1          4         27]
 [       256       3125      46656]
 [    823543   16777216          0]
 [1410065408          1 -251658240]], shape=(4, 3), dtype=int32)
