<a href="https://colab.research.google.com/github/taharamay123/my-codes/blob/main/1_7_1_55.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np

In [8]:
tensor_indexed=tf.constant([2,3,4,5,6,7,8,9,10])
print(tensor_indexed)
print(tensor_indexed[0:5])
print(tensor_indexed[2:6])
print(tensor_indexed[1:8:3])

tf.Tensor([ 2  3  4  5  6  7  8  9 10], shape=(9,), dtype=int32)
tf.Tensor([2 3 4 5 6], shape=(5,), dtype=int32)
tf.Tensor([4 5 6 7], shape=(4,), dtype=int32)
tf.Tensor([3 6 9], shape=(3,), dtype=int32)


Multi dimensional arrays

In [23]:
tensor_two_d=tf.constant([[1,2,3],
                  [4,5,6],
                  [7,8,9],
                  [10,11,12]])
print(tensor_two_d[-1,0:3])

tf.Tensor([10 11 12], shape=(3,), dtype=int32)


In [28]:
tensor_three_d=tf.constant([
    [[1,2,3],
    [4,5,6],],
 [   [7,8,9],
    [10,11,12],
]
])
print(tensor_three_d[0,0:2,0:2])

tf.Tensor(
[[1 2]
 [4 5]], shape=(2, 2), dtype=int32)
