<a href="https://colab.research.google.com/github/taharamay123/my-codes/blob/main/1hourvideo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
import numpy as np

In [3]:
tensor_zero_d=tf.constant(4)
print(tensor_zero_d)
# //it is for creating zero dimensional tensors

tf.Tensor(4, shape=(), dtype=int32)


In [4]:
tensor_one_d=tf.constant([2,0,3,4/5])
print(tensor_one_d)

tf.Tensor([2.  0.  3.  0.8], shape=(4,), dtype=float32)


In [ ]:
t=tensor_one_d
print(t[1])

tf.Tensor(0.0, shape=(), dtype=float32)


In [ ]:
tensor_two_d=tf.constant(
    [[2,0,3,45],
    [4,5,6,7],
     [7,8,9,10]])
print(tensor_two_d)

tf.Tensor(
[[ 2  0  3 45]
 [ 4  5  6  7]
 [ 7  8  9 10]], shape=(3, 4), dtype=int32)


In [ ]:
u=tensor_two_d
print(u[2,3])

tf.Tensor(10, shape=(), dtype=int32)


In [ ]:
tensor_three_d=tf.constant([
    [[2,1,3,4],
    [4,5,6,7]],

    [[7,8,9,10],
     [1,1,1,1]]
    ])

print(tensor_three_d)

tf.Tensor(
[[[ 2  1  3  4]
  [ 4  5  6  7]]

 [[ 7  8  9 10]
  [ 1  1  1  1]]], shape=(2, 2, 4), dtype=int32)


In [ ]:
v=tensor_three_d
print(v[1,1,3])

tf.Tensor(1, shape=(), dtype=int32)


In [ ]:
tensor_four_d=tf.constant(
     [[[[1 ,1 , 3 , 4],
     [ 4 , 5 , 6 , 7]],

     [[ 2 , 8 , 9, 10],
     [ 1  ,1  ,1 , 1]]],
   [ [[3, 2 ,3, 4],
     [5, 6, 7, 8]],
     [[11 ,12 ,13 ,14],
     [5 ,31, 7, 2]] ]
])

In [ ]:
w=tensor_four_d
print(w[0,0,0,3])

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
print(tensor_four_d
      )

tf.Tensor(
[[[[ 1  1  3  4]
   [ 4  5  6  7]]

  [[ 2  8  9 10]
   [ 1  1  1  1]]]


 [[[ 3  2  3  4]
   [ 5  6  7  8]]

  [[11 12 13 14]
   [ 5 31  7  2]]]], shape=(2, 2, 2, 4), dtype=int32)


In [ ]:
a=tensor_four_d+tensor_four_d
print(a)

tf.Tensor(
[[[[ 2  2  6  8]
   [ 8 10 12 14]]

  [[ 4 16 18 20]
   [ 2  2  2  2]]]


 [[[ 6  4  6  8]
   [10 12 14 16]]

  [[22 24 26 28]
   [10 62 14  4]]]], shape=(2, 2, 2, 4), dtype=int32)


In [ ]:
b=2+tensor_four_d
print(b)
c=2*tensor_four_d
print(c)
d=tensor_four_d/2

tf.Tensor(
[[[[ 3  3  5  6]
   [ 6  7  8  9]]

  [[ 4 10 11 12]
   [ 3  3  3  3]]]


 [[[ 5  4  5  6]
   [ 7  8  9 10]]

  [[13 14 15 16]
   [ 7 33  9  4]]]], shape=(2, 2, 2, 4), dtype=int32)
tf.Tensor(
[[[[ 2  2  6  8]
   [ 8 10 12 14]]

  [[ 4 16 18 20]
   [ 2  2  2  2]]]


 [[[ 6  4  6  8]
   [10 12 14 16]]

  [[22 24 26 28]
   [10 62 14  4]]]], shape=(2, 2, 2, 4), dtype=int32)


In [ ]:
d=tf.concat([w,w,w], axis=-1)
e=tf.concat([w,w,w], axis=0)
f=tf.concat([w,w,w], axis=1)
g=tf.concat([w,w,w], axis=2)
h=tf.concat([w,w,w], axis=3)

print(w)
print("axis=-1")

print(d)
print("axis=0")
print(e)
print("axis=1")
print(f)
print("axis=2")
print(g)
print("axis=3")
print(h)

tf.Tensor(
[[[[ 1  1  3  4]
   [ 4  5  6  7]]

  [[ 2  8  9 10]
   [ 1  1  1  1]]]


 [[[ 3  2  3  4]
   [ 5  6  7  8]]

  [[11 12 13 14]
   [ 5 31  7  2]]]], shape=(2, 2, 2, 4), dtype=int32)
axis=-1
tf.Tensor(
[[[[ 1  1  3  4  1  1  3  4  1  1  3  4]
   [ 4  5  6  7  4  5  6  7  4  5  6  7]]

  [[ 2  8  9 10  2  8  9 10  2  8  9 10]
   [ 1  1  1  1  1  1  1  1  1  1  1  1]]]


 [[[ 3  2  3  4  3  2  3  4  3  2  3  4]
   [ 5  6  7  8  5  6  7  8  5  6  7  8]]

  [[11 12 13 14 11 12 13 14 11 12 13 14]
   [ 5 31  7  2  5 31  7  2  5 31  7  2]]]], shape=(2, 2, 2, 12), dtype=int32)
axis=0
tf.Tensor(
[[[[ 1  1  3  4]
   [ 4  5  6  7]]

  [[ 2  8  9 10]
   [ 1  1  1  1]]]


 [[[ 3  2  3  4]
   [ 5  6  7  8]]

  [[11 12 13 14]
   [ 5 31  7  2]]]


 [[[ 1  1  3  4]
   [ 4  5  6  7]]

  [[ 2  8  9 10]
   [ 1  1  1  1]]]


 [[[ 3  2  3  4]
   [ 5  6  7  8]]

  [[11 12 13 14]
   [ 5 31  7  2]]]


 [[[ 1  1  3  4]
   [ 4  5  6  7]]

  [[ 2  8  9 10]
   [ 1  1  1  1]]]


 [[[ 3  2  3  4]
   [ 5  6 

In [ ]:
tensor_one_d=tf.constant([2,0.,-3,8,90],dtype=tf.float32)
casted_one_tensor=tf.cast(tensor_one_d,dtype=tf.float16)
print(tensor_one_d)
print(casted_one_tensor)

tf.Tensor([ 2.  0. -3.  8. 90.], shape=(5,), dtype=float32)
tf.Tensor([ 2.  0. -3.  8. 90.], shape=(5,), dtype=float16)


In [ ]:
tensor_bool=tf.constant([True,False,True])
print(tensor_bool)

tf.Tensor([ True False  True], shape=(3,), dtype=bool)


In [ ]:
tensor_string=tf.constant(["hello","numpy"])
print(tensor_string)

tf.Tensor([b'hello' b'numpy'], shape=(2,), dtype=string)


now we will learn how to convert a numpy array into a tensor

In [ ]:
np_array=np.array([1,2,4])
print(np_array)

[1 2 4]


In [ ]:
converted_tensor= tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 4], shape=(3,), dtype=int64)


In [ ]:
eye_tensor=tf.eye(
    num_rows=3,
    num_columns=3,
    batch_shape=(3,),
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]], shape=(3, 3, 3), dtype=float32)


In [ ]:
fill_tensor=tf.fill([4,3,4],100,name=None
)
print(fill_tensor)

tf.Tensor(
[[[100 100 100 100]
  [100 100 100 100]
  [100 100 100 100]]

 [[100 100 100 100]
  [100 100 100 100]
  [100 100 100 100]]

 [[100 100 100 100]
  [100 100 100 100]
  [100 100 100 100]]

 [[100 100 100 100]
  [100 100 100 100]
  [100 100 100 100]]], shape=(4, 3, 4), dtype=int32)


In [ ]:
ones_tensors=tf.ones([5,3])
print(ones_tensors)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(5, 3), dtype=float32)


In [ ]:
ones_fill_tensors=tf.ones_like(fill_tensor)
print(fill_tensor)
print(ones_fill_tensors)

tf.Tensor(
[[[100 100 100 100]
  [100 100 100 100]
  [100 100 100 100]]

 [[100 100 100 100]
  [100 100 100 100]
  [100 100 100 100]]

 [[100 100 100 100]
  [100 100 100 100]
  [100 100 100 100]]

 [[100 100 100 100]
  [100 100 100 100]
  [100 100 100 100]]], shape=(4, 3, 4), dtype=int32)
tf.Tensor(
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]], shape=(4, 3, 4), dtype=int32)


In [ ]:
print(tf.shape(fill_tensor))
print(tf.size(fill_tensor))

tf.Tensor([4 3 4], shape=(3,), dtype=int32)
tf.Tensor(48, shape=(), dtype=int32)
