<a href="https://colab.research.google.com/github/taharamay123/my-codes/blob/main/DAY1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [6]:
tensor_zero_d=tf.constant(4)
print(tensor_zero_d)
# //it is for creating zero dimensional tensors

tf.Tensor(4, shape=(), dtype=int32)


In [12]:
tensor_one_d=tf.constant([2,0,3,4/5])
print(tensor_one_d)

tf.Tensor([2.  0.  3.  0.8], shape=(4,), dtype=float32)


In [15]:
tensor_two_d=tf.constant(
    [[2,0,3,45],
    [4,5,6,7],
     [7,8,9,10]])
print(tensor_two_d)

tf.Tensor(
[[ 2  0  3 45]
 [ 4  5  6  7]
 [ 7  8  9 10]], shape=(3, 4), dtype=int32)


In [20]:
tensor_three_d=tf.constant([
    [[2,1,3,4],
    [4,5,6,7]],

    [[7,8,9,10],
     [1,1,1,1]]
    ])

print(tensor_three_d)

tf.Tensor(
[[[ 2  1  3  4]
  [ 4  5  6  7]]

 [[ 7  8  9 10]
  [ 1  1  1  1]]], shape=(2, 2, 4), dtype=int32)
